on:
  push:

name: bookdown

jobs:
  build:
    runs-on: [self-hosted, research]
    container: rocker/r-base:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          R -e 'install.packages("data.table")'

      - name: Check
        run: |
          R -e 'CMD check latrend --ignore-vignettes --no-examples'

      - name: Build
        run: |
          R -e 'CMD build latrend --no-build-vignettes'


