on:
  push:

name: latrend 

jobs:
  build:
    runs-on: [self-hosted, research]
    container: rocker/r-base:3.6.3
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install curl
        if: runner.os == 'Linux'
        run: apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -yq libcurl4-openssl-dev libssl-dev libxml2-dev xorg libx11-dev libglu1-mesa-dev libgsl-dev && ldd /usr/local/bin/curl | grep libcurl
        
      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
            
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          options(configure.args = list(rgl = "--disable-ftgl"), 
                  configure.vars = list(curl = "LIBS='-lz -lcrypto -lssl -ldl'"))
          renv::restore()
          
      - name: Check
        run: |
          R -e 'devtools::check(document = TRUE, build_args = c('--no-build-vignettes'), args=c('--ignore-vignettes', '--no-examples'))'

      - name: Build
        run: |
          R -e 'devtools::build(vignettes=FALSE)'


