on:
  push:

name: latrend 

jobs:
  build:
    runs-on: [self-hosted, research]
    container: rocker/r-base:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'
          R -e 'install.packages("devtools")'
          R -e 'install.packages("data.table")'

      - name: Check
        run: |
          R -e 'devtools::document(roclets = c('rd', 'collate', 'namespace'))'
          R -e 'devtools::check(build_args = c('--no-build-vignettes'))'

      - name: Build
        run: |
          R -e 'devtools::document(roclets = c('rd', 'collate', 'namespace'))'
          R -e 'devtools::build(args = c('--no-build-vignettes'))'


